spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_lms
    username: postgres
    password: Gemini@123

jwt:
  secret: rHI6has1Fahsd52dJiuKajhsypodjkce8jsajd39asudaHiow9knKaT83jTolpA
  issuer: auth0
